project_name: go-errmgt

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - skip: true

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Other'
      order: 999

release:
  github:
    owner: kerzzt
    name: go-errmgt
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## go-errmgt {{.Tag}}
    
    Welcome to this new release of go-errmgt!
    
  footer: |
    ## Docker Images
    
    This is a Go library release - no Docker images are provided.
    
    ## Thanks!
    
    Those were the changes on {{.Tag}}!

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj