name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'v1/**'
      - '.github/workflows/**'
  push:
    branches: [ main ]
    paths:
      - 'v1/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.25']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.go-version }}-
    
    - name: Download dependencies
      working-directory: ./v1
      run: go mod download
    
    - name: Verify dependencies
      working-directory: ./v1
      run: go mod verify
    
    - name: Run go vet
      working-directory: ./v1
      run: go vet ./...
    
    - name: Run tests
      working-directory: ./v1
      run: go test -v -race -coverprofile=coverage.out ./...
    
    - name: Check test coverage
      working-directory: ./v1
      run: |
        go tool cover -func=coverage.out
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        echo "Coverage: $COVERAGE%"
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "Coverage is below 80%"
          exit 1
        fi
    
    - name: Upload coverage to Codecov
      if: matrix.go-version == '1.25'
      uses: codecov/codecov-action@v3
      with:
        file: ./v1/coverage.out
        flags: unittests
        name: codecov-umbrella

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: ./v1
        args: --timeout=5m

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    
    - name: Build
      working-directory: ./v1
      run: go build ./...
    
    - name: Check go mod tidy
      working-directory: ./v1
      run: |
        go mod tidy
        git diff --exit-code -- go.mod go.sum
