name: Tag and Release

on:
  push:
    branches: [ main ]
    paths:
      - 'v1/**'

permissions:
  contents: write
  packages: write

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Run tests
      working-directory: ./v1
      run: go test -v -race ./...
    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
        custom_release_rules: |
          feat:minor,
          fix:patch,
          docs:patch,
          chore:patch,
          style:patch,
          refactor:patch,
          perf:patch,
          test:patch,
          build:patch,
          ci:patch,
          revert:patch,
          BREAKING CHANGE:major
    
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      if: steps.tag_version.outputs.new_tag
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run GoReleaser
      if: steps.tag_version.outputs.new_tag
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
        workdir: ./v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}